name: test-1
on: workflow_dispatch
jobs:
  checkout-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Build with Maven
        run: mvn clean install

      - name: Configure Git user
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Update version in pom.xml
        run: |
          # Use sed to update only the <version> tag under <project> context
          new_version="1.0.21"  # Desired release version
          sed -i '/<project/,/<\/project>/ s|<version>1.0.20-SNAPSHOT</version>|<version>'"${new_version}"'</version>|' pom.xml

      - name: Commit version change
        run: |
          # Commit the version change to git
          git add pom.xml
          git commit -m "Update version to ${new_version}"
          git push origin HEAD
